sources:
  - name: my-api
    handler:
      openapi:
        source: ./sources/api.json
        endpoint: https://my-api.com/
        operationHeaders:
          Content-Type: application/json
          Accept: application/json
